### ISSUE TITLE
Invoice numbers won't increment properly using static preferences

### ISSUE THREAD

**Issue by jhawthorn** [solidusio-contrib/solidus_print_invoice#13]
When using static preferences (the new default) invoice numbers won't increment properly and will be reset when the server restarts.

The next invoice number is [stored as a preference](https://github.com/solidusio-contrib/solidus_print_invoice/blob/69c2f0e61f7bf056775fc813f8a84a7b0bd88d46/app/models/spree/print_invoice_configuration.rb#L4), which has never been a safe way to do this and should never have been done. Nonetheless, with our change to static preferences it now basically doesn't work at all.

We should move this to a database table or use order.id or similar.

**Comment by jtapia** [comment]
@jhawthorn what do you think to use https://github.com/djreimer/sequenced or are you thinking in an integer row on the DB?
