### ISSUE TITLE
 NoMethodError in Spree::Admin::Orders#show

### ISSUE THREAD

**Issue by hkleow** [solidusio-contrib/solidus_print_invoice#42]
```
`im = Sprockets::Railtie.build_environment(Rails.application).find_asset(Spree::PrintInvoice::Config[:print_invoice_logo_path])
image im.filename , :at => [0,720], :scale => logo_scale

fill_color "E99323"
if @hide_prices
`

```

my spree.rb 
`Spree::PrintInvoice::Config.set(print_invoice_logo_path:  "/path/to/public/images/logoserp.jpg")
`

not sure why it keep giving me this error, i've place my logo under public/images folder

**Comment by aldesantis** [comment]
@hkleow sorry, could you send the full stacktrace and format it properly? Thanks!
