### ISSUE TITLE
Inclusion of SolidusSupport::EngineExtensions causes load order issues for Solidus apps with controller extensions

### ISSUE THREAD

**Issue by zachfeldman** [solidusio-contrib/solidus_print_invoice#62]
Hi there, we were trying to use this gem as-is in our Solidus app, but found that for some reason when the line `include SolidusSupport::EngineExtensions` is present, our controllers extended from Solidus core are not being loaded. With this line, methods that we've overriden end up being defined in core Solidus code instead, and without this line, our overridden definition is included.

Another reason that we're unable to use this gem as-is is its inclusion of just `solidus` as a dependency, which caused a lot of changes to our `Gemfile.lock` including pinning specific versions of Rails.

I don't have time to dig in further as to why the load order problem is present so will likely just be using this gem as an example to follow, but wanted to at least make the authors of them aware of the app, and provide a place for others to troubleshoot if they also see this issue.

**Comment by zachfeldman** [comment]
Nice, super helpful stale bot there closing valid issues...

**Comment by senemsoy** [comment]
hi @zachfeldman, I think this issue was caused by bumping the requirement for `solidus_support` to `0.9` here: https://github.com/solidusio-contrib/solidus_print_invoice/commit/d89bb001ab4ea937013b9b866fc88f8e9837db4f

you can read more about it here: https://github.com/solidusio/solidus_support/issues/73

**Comment by zachfeldman** [comment]
Thanks @senemsoy , unfortunately we ended up just copying the code here and integrating it internally in our app instead of using the gem :-1: feelsbadman.jpg
