### ISSUE TITLE
Tax amount are itemized

### ISSUE THREAD

**Issue by ahwong5** [solidusio-contrib/solidus_print_invoice#7]
Tax amount are itemized instead of sum up together. Just imagine if in the order there are 10 products, there will be at least 10 lines of tax amount.

Would appreciate advising on how to fix it? 

TQ!

![screen shot 2017-06-15 at 7 49 57 pm](https://user-images.githubusercontent.com/17537158/27180365-b924f41a-5205-11e7-90b0-0e5264c63a4e.jpg)

**Comment by Senjai** [comment]
@ahwong5 This is probably an artifact from when we always used to do order level promotions. 

You can fix this by adding a Tax Total column to each line item. And using the orders tax total after the sub total.

**Comment by ahwong5** [comment]
@Senjai Thanks for your tips. I will work hard to learn to fix it. Am very new to coding world, Rails as well as Solidus  :)

**Comment by danmitchell-** [comment]
I've also come across this issue so will look to get a PR raised 👍
